root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app ./cmd/chatd"
  bin = "tmp/app"
  full_bin = true
  include_ext = ["go", "tpl", "html"]
  exclude_dir = ["tmp", "vendor"]

[log]
  time = true